### ISSUE TITLE
Option to sponsor?

### ISSUE THREAD

**Issue by raryanpur** [silitics/rugpi#18]
This is a great project and I think the community will benefit a ton from it. The SBC community needs more projects like this. Have you thought about including an option for sponsoring this work (would be happy to sponsor!)

**Comment by koehlma** [comment]
Thank you for the warm and encouraging words! I really appreciate that.

Also, thanks for offering to sponsor. In the long run, I would love to find a way to make Rugpi financially viable and ensure its proper maintenance and development, especially when it gains further traction and adoption. So far, however, I have no concrete plans for how this may look like, in particular since this is a young project and also the first public project of my company (Silitics), which I just founded. Towards the end of the year, I hope to have a clearer idea where this project (and my company) is going. With regard to sponsorships, I would first have to check how this would work from a tax perspective. Currently, however, this is not a priority, as my focus is on building a successful project and finishing my PhD.
