### ISSUE TITLE
Can't log in (default credentials unknown) - "rpi-raspios" template

### ISSUE THREAD

**Issue by JosephM101** [silitics/rugpi#38]
Trying out Rugpi for the first time. I've built the `rpi-raspios` template for a Raspberry Pi 4 (`tryboot-pi4`). Wanted to log in to set up Wi-Fi, but found that I couldn't.

Upon booting the device, I noticed that on TTY1 (default), a getty is never started; the boot messages remain on screen. Not sure if this is intended behavior, but switching to TTY2 did give me a login prompt.

I attempted to log in as `root` with various passwords, such as `raspberry`, `root`, and `rugpi`, none of which worked. There's no obvious way for me to tell how to log in, and no amount of internet digging surfaced any answers (they all thought I was asking about the official Raspberry Pi OS distro, since `rugpi`'s name has a similarity.)

Is there a recipe I need to add to allow local login? An SSH recipe appears to be available, but I'm unaware of how to set it up, and my login attempts were all rejected.

**Comment by koehlma** [comment]
Indeed, there are no default credentials. We also intentionally strip all of Raspberry Pi OS's user setup. Default credentials pose a security risk and setting up users should be done with recipes in the image. By default, any changes that you make after booting (WiFi, users, et cetera) will also not survive a reboot due to Rugpi's build-in state management (see https://oss.silitics.com/rugpi/docs/guide/state-management for details).

There is no recipe for setting up users. As you can do anything within a recipe that you can do with a shell script, the usual commands like `adduser` and `passwd` can be used to add users or set their passwords (logging in on the console should then also work). Again, I would recommend against doing that for production images for security concerns.

You can add public keys to the parameters of the SSH recipe:

https://github.com/silitics/rugpi/blob/5d0c2d9238ddfc357fb8917eb954cdd2c56210ae/bakery/templates/rpi-raspios/layers/customized.toml#L27-L30

Password login should work, if you set a password for the respective user first.

I hope, this helps. :)

I will close this issue as we will not add default credentials.
